pragma Singleton

import Quickshell

Singleton {
    property string primary: "#ffb3ae"
    property string primaryFixed: "#ffdad7"
    property string primaryFixedDim: "#ffb3ae"
    property string on_primary: "#571e1c"
    property string on_primaryFixed: "#3b0909"
    property string on_primaryFixedVariant: "#733330"
    property string primaryContainer: "#733330"
    property string on_primaryContainer: "#ffdad7"
    property string secondary: "#e7bdb9"
    property string secondaryFixed: "#ffdad7"
    property string secondaryFixedDim: "#e7bdb9"
    property string on_secondary: "#442927"
    property string on_secondaryFixed: "#2c1513"
    property string on_secondaryFixedVariant: "#5d3f3d"
    property string secondaryContainer: "#5d3f3d"
    property string on_secondaryContainer: "#ffdad7"
    property string tertiary: "#e2c28c"
    property string tertiaryFixed: "#ffdea6"
    property string tertiaryFixedDim: "#e2c28c"
    property string on_tertiary: "#402d04"
    property string on_tertiaryFixed: "#271900"
    property string on_tertiaryFixedVariant: "#594319"
    property string tertiaryContainer: "#594319"
    property string on_tertiaryContainer: "#ffdea6"
    property string error: "#ffb4ab"
    property string on_error: "#690005"
    property string errorContainer: "#93000a"
    property string on_errorContainer: "#ffdad6"
    property string surface: "#1a1111"
    property string on_surface: "#f1dedd"
    property string on_surfaceVariant: "#d8c2bf"
    property string outline: "#a08c8a"
    property string outlineVariant: "#534342"
    property string shadow: "#000000"
    property string scrim: "#000000"
    property string inverseSurface: "#f1dedd"
    property string inverse_on_surface: "#382e2d"
    property string inversePrimary: "#904a46"
    property string surfaceDim: "#1a1111"
    property string surfaceBright: "#423736"
    property string surfaceContainerLowest: "#140c0b"
    property string surfaceContainerLow: "#231919"
    property string surfaceContainer: "#271d1d"
    property string surfaceContainerHigh: "#322827"
    property string surfaceContainerHighest: "#3d3231"
}
