pragma Singleton

import Quickshell

Singleton {
    property string primary: "{{colors.primary.default.hex}}"
    property string primaryFixed: "{{colors.primary_fixed.default.hex}}"
    property string primaryFixedDim: "{{colors.primary_fixed_dim.default.hex}}"
    property string on_primary: "{{colors.on_primary.default.hex}}"
    property string on_primaryFixed: "{{colors.on_primary_fixed.default.hex}}"
    property string on_primaryFixedVariant: "{{colors.on_primary_fixed_variant.default.hex}}"
    property string primaryContainer: "{{colors.primary_container.default.hex}}"
    property string on_primaryContainer: "{{colors.on_primary_container.default.hex}}"
    property string secondary: "{{colors.secondary.default.hex}}"
    property string secondaryFixed: "{{colors.secondary_fixed.default.hex}}"
    property string secondaryFixedDim: "{{colors.secondary_fixed_dim.default.hex}}"
    property string on_secondary: "{{colors.on_secondary.default.hex}}"
    property string on_secondaryFixed: "{{colors.on_secondary_fixed.default.hex}}"
    property string on_secondaryFixedVariant: "{{colors.on_secondary_fixed_variant.default.hex}}"
    property string secondaryContainer: "{{colors.secondary_container.default.hex}}"
    property string on_secondaryContainer: "{{colors.on_secondary_container.default.hex}}"
    property string tertiary: "{{colors.tertiary.default.hex}}"
    property string tertiaryFixed: "{{colors.tertiary_fixed.default.hex}}"
    property string tertiaryFixedDim: "{{colors.tertiary_fixed_dim.default.hex}}"
    property string on_tertiary: "{{colors.on_tertiary.default.hex}}"
    property string on_tertiaryFixed: "{{colors.on_tertiary_fixed.default.hex}}"
    property string on_tertiaryFixedVariant: "{{colors.on_tertiary_fixed_variant.default.hex}}"
    property string tertiaryContainer: "{{colors.tertiary_container.default.hex}}"
    property string on_tertiaryContainer: "{{colors.on_tertiary_container.default.hex}}"
    property string error: "{{colors.error.default.hex}}"
    property string on_error: "{{colors.on_error.default.hex}}"
    property string errorContainer: "{{colors.error_container.default.hex}}"
    property string on_errorContainer: "{{colors.on_error_container.default.hex}}"
    property string surface: "{{colors.surface.default.hex}}"
    property string on_surface: "{{colors.on_surface.default.hex}}"
    property string on_surfaceVariant: "{{colors.on_surface_variant.default.hex}}"
    property string outline: "{{colors.outline.default.hex}}"
    property string outlineVariant: "{{colors.outline_variant.default.hex}}"
    property string shadow: "{{colors.shadow.default.hex}}"
    property string scrim: "{{colors.scrim.default.hex}}"
    property string inverseSurface: "{{colors.inverse_surface.default.hex}}"
    property string inverse_on_surface: "{{colors.inverse_on_surface.default.hex}}"
    property string inversePrimary: "{{colors.inverse_primary.default.hex}}"
    property string surfaceDim: "{{colors.surface_dim.default.hex}}"
    property string surfaceBright: "{{colors.surface_bright.default.hex}}"
    property string surfaceContainerLowest: "{{colors.surface_container_lowest.default.hex}}"
    property string surfaceContainerLow: "{{colors.surface_container_low.default.hex}}"
    property string surfaceContainer: "{{colors.surface_container.default.hex}}"
    property string surfaceContainerHigh: "{{colors.surface_container_high.default.hex}}"
    property string surfaceContainerHighest: "{{colors.surface_container_highest.default.hex}}"
}
